# Generated by Django 5.1.6 on 2025-02-14 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_oder',
            new_name='date_order',
        ),
    ]
